[book]
title = "Cosmos Developer Academy Book"
description = "It is the online book version of the Cosmos Developer Academy Course."
author = "Author: Interchain Developer Academy, Editor: Jammyaa"

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/nebula-labs/cosmos-developer-academy-book"

[rust]
edition = "2021"
